# Population size

Code to generate Figure 2 showing the effect of different parameters on the population size of rescued populations.

In [9]:
run rescue_theory.py

In [3]:
m = M(.01, .02, .001)
m

array([[9.8901e-01, 9.9000e-04],
       [0.0000e+00, 1.0098e+00]])

In [6]:
m2 = np.dot(m, m)
m2

array([[0.97814078, 0.00197882],
       [0.        , 1.01969604]])

In [7]:
m3 = np.dot(m2, m)
m3

array([[0.96739101, 0.00296657],
       [0.        , 1.02968906]])

In [8]:
Mn(.01, .02, .001, 3)

array([[0.96739101, 0.00296657],
       [0.        , 1.02968906]])

In [12]:
Zn(10000, 0, .01, .02, .0001, 2000)

14707425647.46274